# Generated by Django 6.0.4 on 2026-04-19 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Post ssenariysi yoki matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='planner/images/')),
                ('post_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Tasdiq kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Inkor qilindi'), ('published', 'Post qilindi')], default='draft', max_length=20)),
                ('feedback', models.TextField(blank=True, help_text="Mijozning e'tirozlari (Reject bo'lsa)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='clients.client')),
            ],
        ),
    ]
