# Generated by Django 6.0.4 on 2026-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_price_at_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
