# Generated by Django 6.0.4 on 2026-04-28 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +998901234567', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami noto'g'ri formatda yoki operator kodi xato (masalan: +998901234567).", regex='^\\+998(33|50|70|77|88|90|91|93|94|95|97|98|99)\\d{7}$')]),
        ),
    ]
