# Generated by Django 6.0.4 on 2026-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video_limit', models.PositiveIntegerField(default=0)),
                ('post_limit', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
