# Generated by Django 6.0.4 on 2026-04-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='post_limit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='video_limit',
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('video', 'Video'), ('post', 'Post'), ('story', 'Story'), ('reels', 'Reels')], default='post', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
