# Generated by Django 6.0.4 on 2026-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('insta_username', models.CharField(blank=True, max_length=100, null=True)),
                ('insta_password', models.CharField(blank=True, max_length=255, null=True)),
                ('current_followers', models.PositiveIntegerField(default=0)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
