# Generated by Django 6.0.4 on 2026-04-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='initial_followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
