# Generated by Django 6.0.4 on 2026-04-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_initial_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='post_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='reels_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='story_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='video_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
