# Generated by Django 6.0.4 on 2026-04-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_post_limit_client_reels_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
